language: java
 jdk:
  - oraclejdk8 
deploy:
  provider: heroku
  api_key:
   secure: "WhJpjTrm8iMgwTiUrzZhci9DbPrgRoTRkm6uBTuoqN9p7XhSbMHA1NK2o+Zhzh1COfYQCuxrLTIhsiHV+0pG9SBSENtz6qWM+BcKINIrvlXTcYY1z0NzlBdp4CVeelmKf6HuEDd80cJFRIU1nJzetp/v8RxppiBcmpFepC79twDekn1E5L3W6fwSF7he17IhLcG0DdRQVIDOQyJ8TalP0b6kWmGQqGMRuCpyDGK8aaPK930rkbcnhw/IspWc+JAFCjOScbejkF1JKqebhGM9+F6gTIgH8rInbd5TgoZDnt2Ce8hW2qGE4oTnrq5aX9sQAxH2HoaY7QTkjD18oRh2mSDYHVuoRdpquF8Viaoz2SBHJMvE4V+lAeec2bLsO491RVhirxJ+L+tErJXnJZTvGc5+ARhKXGRXwV3YwiENysVo5MCSy+rSCvXiG8KgExaHWNnbObn9zs/h37H5JkZH2j09YSDiQ7IACJRTESBCBhJcBRPlv7uqkSvooa+JhbfAyoKhkjd6hBFCuiU4tsOo7ndmO+hGCP+7xqbbNfh8I/NXm0RAN6R+W7cLzXlNk8dPzBxMOFJPOa49I7S4/yDXWFUgxBdNO0D81pEu9Xs1aW6odGE5IWAmGkWiAqDM+OiQBHhBSvdtXy9Kf8wAfgXV4Tsmw/uNPxMGV3WUcbKvOKk="
  app: ci-spring-boot2